#!/usr/bin/env python

# Copyright 2014 Jay Conrod. All rights reserved.

# This file is part of CodeSwitch. Use of this source code is governed by
# the 3-clause BSD license that can be found in the LICENSE.txt file.


import os.path
import sys
import yaml


if len(sys.argv) != 3:
    sys.stderr.write("usage: %0 flags.yaml flags.h\n" % sys.argv[0])
    sys.exit(1)


flagsYamlFileName = sys.argv[1]
flagsHFileName = sys.argv[2]

with open(flagsYamlFileName) as flagsYamlFile:
    flags = yaml.load(flagsYamlFile.read())

with open(flagsHFileName, "w") as flagsHFile:
    flagsHFile.write("""// DO NOT MODIFY
// This file was automatically generated by gen_opcodes.py

#ifndef flags_h
#define flags_h

namespace codeswitch {
namespace internal {

enum Flag {
""")
    for i, flag in enumerate(flags):
        flagsHFile.write("  %s_FLAG = 1 << %d,\n" % (flag, i))
    flagsHFile.write("  NUM_FLAGS = %d" % i)
    flagsHFile.write("""
};

}
}

#endif
""")
