#!/usr/bin/env python

# Copyright Jay Conrod. All rights reserved.

# This file is part of CodeSwitch. Use of this source code is governed by
# the 3-clause BSD license that can be found in the LICENSE.txt file.


import sys
import yaml

if len(sys.argv) != 3:
    sys.stderr.write("usage: %s opcodes.yaml opcodes.h\n" % sys.argv[0])
    sys.exit(1)

opcodesYamlName = sys.argv[1]
opcodesHName = sys.argv[2]

with open(opcodesYamlName) as opcodesYamlFile:
    opcodes = yaml.load(opcodesYamlFile.read())

with open(opcodesHName, "w") as opcodesHFile:
    opcodesHFile.write("""// DO NOT MODIFY
// This file was automatically generated by gen_opcodes.py

#ifndef opcodes_h
#define opcodes_h

namespace codeswitch {
namespace internal {

enum Opcode {
""")
    for opc in opcodes:
        name = opc["name"].upper()
        if name == "NULL":
            name = "NUL"
        opcodesHFile.write("  %s,\n" % name)
    opcodesHFile.write("""  NUM_OPCODES,
  LAST_OPCODE = NUM_OPCODES - 1
};

}
}

#endif
""")
