py_binary(
    name = "format_everything",
    srcs = [
        "format_everything.py",
        "formatter.py",
        "rewriter.py",
    ],
    main = "format_everything.py",
    deps = ["//gypsum"],
)
